name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "where we are at:"
      - run: echo ls $(ls)

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./server/gradlew

      - run: echo "where we are at:"
      - run: echo ls $(ls)

      - name: Change the current dir to server
        run: cd server
        
      - name: Build Java with Gradle
      - run: ./gradlew build
      
      - name: Build Docker Image
        run: |
          docker build -t java-server .
          echo ${docker image ls}
    
       #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       #- run: echo "🖥️ The workflow is now ready to test your code on the runner."
       #- name: List files in the repository
        # run: |
          # ls ${{ github.workspace }}
      # - run: echo "🍏 This job's status is ${{ job.status }}."
